package com.itsmamme.enums;

public enum Side {
    TOP_LEFT_CORNER,
    TOP_RIGHT_CORNER,
    BOTTOM_LEFT_CORNER,
    BOTTOM_RIGHT_CORNER,

    TOP_JUNCTION,
    BOTTOM_JUNCTION,
    LEFT_JUNCTION,
    RIGHT_JUNCTION,

    CROSS_JUNCTION,

    VERTICAL_LINE,
    HORIZONTAL_LINE
}
